name: Lint Python Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Super-Linter
        uses: github/super-linter@v6.6.0

      - name: Lint Python Code
        env:
          DEFAULT_BRANCH: main  # Adjust if your default branch is different
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          super-linter --format yaml --no-color --find-issues .
